sudo: required

language: python

env:
  - BUILD_TARGET=sketch
  - BUILD_TARGET=tests

install:
  - sudo sh prepare.sh
  - sh init.sh

script:
  - sh increment-version.sh
  - sh inject-version.sh
  - sh build-$BUILD_TARGET.sh
